version: "3.9"

services:
  api:
    build: 
      context: ./backend_api
      dockerfile: Dockerfile
    image: backend_api:latest
    container_name: myapi
    ports:
      - "5000:5000"
    depends_on:
      - postgresdb
    networks:
      - backend
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=postgresdb;Port=5432;Database=mylabsdb;Username=admin;Password=developer

  frontend:
    build:
      context: ./frontend_next
      dockerfile: Dockerfile
    image: frontend_next:latest
    container_name: react_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - backend
  
  frontend-node:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend_next:/app
      - /app/node_modules


  postgresdb:
    image: postgres:16
    container_name: postgresdb
    networks:
      - backend
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: mylabsdb
    ports:
      - "5432:5432"

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: